#spring
spring:
  datasource:
    url: jdbc:mysql:///dsxcj?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/#等前端
    suffix: .html

#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/sys/*.xml

#server
server:
  port: 80
  tomcat:
    max-threads: 1000
  servlet:
    context-path: /

#LOG
logging:
  level:
    com.mjk: DEBUG