#spring
spring:
  datasource:
    url: jdbc:mysql:///dsxcj?serverTimezone=GMT
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/jsp/
    suffix: .html

#mybatis
mybatis-plus:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
    classpath:/mapper/*.xml
  type-aliases-package: com.abc.shop.dao

#server
server:
  port: 80
  tomcat:
    max-threads: 1000
  servlet:
    context-path: /

#LOG
logging:
  level:
    com.abc: DEBUG